[Main]
isGegga=0

[GUI]
isConsole=1
isDeviceMsg=1

[Console]
isDebug=false
ColorBack=#000000
ColorDebug=#5280ca
ColorInfo=#48ab30
ColorWarning=#eb9c34
ColorError=#eb4034
ColorFatal=#305fab

[MQTT]
address="herdmind-mqtt.vereni.net"
port=7883
username="USERNAME"
password="PASSWORD"
gatewayId="7812164701badcab"

[Chirpstack]
# see bolus_chirpstack.js and collar_chirpstack.js in res dir for the format
# isJson=1

apiUrl="http://chirpstack-rest-api.vereni.net"
apiPort=7790

# Web UI
# https://chirpstack.vereni.net
# user:admin
# pass:09OrLoS1DpBy53qZSZj4t+XEKWqQWppG2QZlQKeORBg

#Obtained from Chirpstack Web UI (Newtork server)
apiKey="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6Ijg1MmRiMWZhLTViMjktNDhmNi04ZjRhLWViOTViNjNlNzhmNyIsInR5cCI6ImtleSJ9.svOFy7py6rCfOs5Ra-weYoapquactWzgQhipHTzsm3Y"

#Obtained from Chirpstack Web UI - register Herdmind-simulator as an application to get the ID
appId="616c93c8-09bb-4b15-8fcc-611458050abb"

#Obtained from Chirpstack Web UI - register application profile (Bolus)
bolusProfileId="2b04b38b-87a9-4d6b-a802-b5bcf9606557"

#Obtained from Chirpstack Web UI - register application profile (Collar)
collarProfileId="e770ddf8-8f41-47cf-94ad-0e2a960b3cb4"

#Obtained from Chirpstack Web UI - register application profile (Gateway)
gatewayProfileId="70127acc-99cc-4e81-8291-b25322b0a7ba"

#Obtained from Chirpstack - used for propper ABP address generation
#in /etc/chirpstack/chirpstack.toml, section [network], net_id
netId="000000"

