[Main]
isGegga=0

[GUI]
isConsole=1
isDeviceMsg=1
isLoadLast=1

[Console]
isDebug=false
ColorBack=#000000
ColorDebug=#5280ca
ColorInfo=#48ab30
ColorWarning=#eb9c34
ColorError=#eb4034
ColorFatal=#305fab

[MQTT]
address="localhost"
port=1883
username=""
password=""
gatewayId="7812164701badcab"

[Chirpstack]
# see bolus_chirpstack.js and collar_chirpstack.js in res dir for the format
# isJson=0

apiUrl="http://localhost"
apiPort=8090

#Obtained from Chirpstack Web UI - register Herdmind-simulator as an application to get the ID
appId="64997b93-62fa-4955-980a-6d03a1ff4322"

#Obtained from Chirpstack Web UI
apiKey="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6IjU0YWJmZDYxLWI3YjQtNDYxNy04MTIxLWQxMTQxMDFlYWRhNCIsInR5cCI6ImtleSJ9.cOKrJZJb6T5Cc8G5GklirGBpPdbLdE1kU0yYbfZEX9o"

tenantId="e0e88c5d-b3b1-4719-b622-130a49ce0dd5"

tenantKey="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6IjMxNzIxYTkyLWU1NWItNDcxNy1hMzI3LTlhNjFjZjhmNDljYSIsInR5cCI6ImtleSJ9.kZBqDNAzwDSgbe1m2b0pjanAMkaeIkI7vyg9eMpDaME"

#Obtained from Chirpstack Web UI - register application profile (Bolus)
bolusProfileId="89532e94-874e-4fcb-8e50-4ebb1b97aa44"

#Obtained from Chirpstack Web UI - register application profile (Collar)
collarProfileId="ae7b6bd0-a68e-4677-a841-b64655ace0d5"

#Obtained from Chirpstack Web UI - register application profile (Gateway)
gatewayProfileId="70127acc-99cc-4e81-8291-b25322b0a7ba"

#Obtained from Chirpstack - used for propper ABP address generation
#in /etc/chirpstack/chirpstack.toml, section [network], net_id
netId="000000"
