#ifndef DEFINES_H
#define DEFINES_H


#define INITIAL_ANIMALS_COUNT 100
#define INITIAL_COLLAR_PERCENTAGE 10
#define INITIAL_HERD_SPREAD 40
#define INITIAL_MEDDOW_SIZE 200


#define ANIMAL_WIDTH 0.6f
#define ANIMAL_LENGTH 1.0f
#define ANIMAL_LENGTH_HALF (ANIMAL_LENGTH * 0.5f)
#define HERD_DIAMETER 80.0f
#define HERD_UPDATE_INTERVAL 10

#define ANIMAL_MAX_SPEED 0.1f
#define ANIMAL_FRICTION 0.01f
#define ANIMAL_ROTATION_FADING 0.03f
#define ANIMAL_ATTRACTION_POWER 0.05f
#define ANIMAL_ATTRACTION_DISTANCE 20.0f
#define ANIMAL_COLLIDING_DISTANCE 2.0f
#define ANIMAL_REPELING_DISTANCE 10.0f

#define BOLUS_TRANSMIT_DISTANCE 6.0f
#define BOLUS_TRANSMIT_ANGLE 40.0f


#endif // DEFINES_H
