#ifndef DEFINES_H
#define DEFINES_H

#define VERSION 0.7

#define PRINT_DEBUG_INFO false

#define INITIAL_ANIMALS_COUNT 100
#define INITIAL_COLLAR_PERCENTAGE 50
#define INITIAL_HERD_SPREAD 40
#define INITIAL_MEDDOW_SIZE 2000

#define ANIMAL_WIDTH 0.6f
#define ANIMAL_LENGTH 1.0f
#define ANIMAL_LENGTH_HALF (ANIMAL_LENGTH * 0.5f)
#define HERD_DIAMETER 80.0f
#define HERD_UPDATE_INTERVAL 10

#define ANIMAL_MAX_SPEED 0.1f
#define ANIMAL_MIN_SPEED 0.002f
#define ANIMAL_WALKING_SPEED 0.03
#define ANIMAL_FRICTION 0.04f
#define ANIMAL_ROTATION_FADING 0.03f
#define ANIMAL_ATTRACTION_POWER 0.05f
#define ANIMAL_ATTRACTION_DISTANCE 20.0f
#define ANIMAL_COLLIDING_DISTANCE 2.0f
#define ANIMAL_AVOID_DISTANCE (ANIMAL_COLLIDING_DISTANCE*2.0f)
#define ANIMAL_REPELING_DISTANCE 10.0f
#define ANIMAL_AVOID_ROTATION_ANGLE 45.0f

#define BOLUS_TRANSMIT_DISTANCE 6.0f
#define BOLUS_TRANSMIT_ANGLE 40.0f

#define MEADOW_INITIAL_DIM_WIDTH 100
#define MEADOW_INITIAL_DIM_HEIGHT 100
#define MEADOW_INITIAL_CAPACITY 1.2f // grass kg per square meter
#define ANIMAL_INITIAL_GRAZING_CAPACITY 12.0f // in kg per day
#define MEADOW_GROWING_SPEED 2.0f

#define LAWN_RADIUS 1.5f
#define LAWN_DIAMETER (LAWN_RADIUS*2.0f)
#define LAWN_ANIMALS_MAX_COUNT 3

#define ANIMAL_STAMINA_MIN 0.001f
#define ANIMAL_STAMINA_MAX 1.0f
#define ANIMAL_STAMINA_STEP 0.1f

#define FARM_INITIAL_LOCATION_LAT 41.613306
#define FARM_INITIAL_LOCATION_LONG 23.912167


#define DEVICES_LIST_FILE "devices.json"
#define ANIMALS_LIST_FILE "animals.json"

#define MAX_COLLAR_GATEWAY_DISTANCE 100

#define PASTURE_GEN_RADIUS 1000.0f
#define PASTURE_GEN_COUNT 100
#define PASTURE_GEN_SMOOTH_IT 5
#define PASTURE_GEN_SCALE 0.01f
#define PASTURE_GEN_AMP_MIN 1.0f
#define PASTURE_GEN_AMP_MAX 200.0f
#define PASTURE_GEN_WAVE_MIN 1.0f
#define PASTURE_GEN_WAVE_MAX 200.0f


#define SAVE_DIR "saves"

#endif // DEFINES_H
