[Main]
isGegga=0

[GUI]
isConsole=1
isDeviceMsg=1
isFocusAnim=1

[Console]
isDebug=false
ColorBack=#000000
ColorDebug=#5280ca
ColorInfo=#48ab30
ColorWarning=#eb9c34
ColorError=#eb4034
ColorFatal=#305fab

[MQTT]
address="localhost"
port=1883
username=""
password=""
gatewayId="7812164701badcab"

[Chirpstack]
# see bolus_chirpstack.js and collar_chirpstack.js in res dir for the format
# isJson=0

apiUrl="http://localhost"
apiPort=8090
tenantId="018047e1-7528-40c9-9d3b-236a35beb5b0"
tenantKey="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6ImIwYTI5YjU2LWY2YzUtNDAyMC04MTUxLWZkNWUxZDYxOWJlZiIsInR5cCI6ImtleSJ9.EKjKWO50QLcQgFSkkSnTf0qoyWfYyecll4tt0XHZpiY"

#Obtained from Chirpstack Web UI
apiKey="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6IjE4NzcyNjBlLTNhZTQtNDVkNC1iYmQ5LTFiYjM2ZjFhMzI4NiIsInR5cCI6ImtleSJ9.F9iwdmBtv6AOQ3Miu8cTGiFglcgf08HXwCEOQgRc6CQ"

#Obtained from Chirpstack Web UI - register Herdmind-simulator as an application to get the ID
appId="b7cdf8cf-0b72-45e9-8f3e-0f8020e5b094"

#Obtained from Chirpstack Web UI - register application profile (Bolus)
bolusProfileId="d842d103-6038-44ec-91d8-00a9c79fce0a"

#Obtained from Chirpstack Web UI - register application profile (Collar)
collarProfileId="729a5bed-1ffd-46c7-852c-5b92bb184a8b"

#Obtained from Chirpstack Web UI - register application profile (Gateway)
gatewayProfileId="70127acc-99cc-4e81-8291-b25322b0a7ba"

#Obtained from Chirpstack - used for propper ABP address generation
#in /etc/chirpstack/chirpstack.toml, section [network], net_id
netId="000000"
