[Main]
isGegga=0

[GUI]
isConsole=1
isDeviceMsg=1

[Console]
isDebug=false
ColorBack=#000000
ColorDebug=#5280cc
ColorInfo=#48ab30
ColorWarning=#eb9c34
ColorError=#eb4034
ColorFatal=#305fab

[MQTT]
address="https://herdmind-mqtt.vereni.net"
port=7883
gatewayId="7812164701badcab"

[Chirpstack]
apiUrl="https://chirpstack-rest-api.vereni.net"
apiPort=7790

# Web UI
# https://chirpstack.vereni.net
# user:admin
# pass:09OrLoS1DpBy53qZSZj4t+XEKWqQWppG2QZlQKeORBg

#Obtained from Chirpstack Web UI
apiKey="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6Ijk3MmQyN2EzLWZiNTMtNDFlNC1iNjU3LTNhYzkyOGEwZWFhOCIsInR5cCI6ImtleSJ9.Oo_P7863XawfPecgKxts61i2q-ZO7ZqXXoRz47mdg3I"

#Obtained from Chirpstack Web UI - register Herdmind-simulator as an application to get the ID
appId="616c93c8-09bb-4b15-8fcc-611458050abb"

#Obtained from Chirpstack Web UI - register application profile (Bolus)
bolusProfileId="2b04b38b-87a9-4d6b-a802-b5bcf9606557"

#Obtained from Chirpstack Web UI - register application profile (Collar)
collarProfileId=" e770ddf8-8f41-47cf-94ad-0e2a960b3cb4"

#Obtained from Chirpstack Web UI - register application profile (Gateway)
gatewayProfileId="70127acc-99cc-4e81-8291-b25322b0a7ba"

#Obtained from Chirpstack - used for propper ABP address generation
#in /etc/chirpstack/chirpstack.toml, section [network], net_id
netId="000000"

