[Main]

[GUI]
isConsole=1
isDeviceMsg=1

[Console]
isDebug=false
ColorBack=#000000
ColorDebug=#5280ca
ColorInfo=#48ab30
ColorWarning=#eb9c34
ColorError=#eb4034
ColorFatal=#305fab

[MQTT]
address="localhost"
port=1883
username=""
password=""

[Chirpstack]
# see bolus_chirpstack.js and collar_chirpstack.js in res dir for the format
# isJson=0

apiUrl="http://localhost"
apiPort=8090

#Global api key. Obtained from Chirpstack Web UI from "Network Server/API Keys" menu
apiKey=""

#Obtained from Chirpstack Web UI - register Herdmind-simulator as tenant to get the ID
# WARNING: SELECT IT AS CURRENT TENANT TO obtain next id's
tenantId=""

#Obtained from Chirpstack Web UI - API key for selected tenant from "Tenant/API Keys" menu
tenantKey=""

#Obtained from Chirpstack Web UI - register Herdmind-simulator as an application to get the ID
appId=""

#Obtained from Chirpstack Web UI - register application profile (Bolus)
bolusProfileId=""

#Obtained from Chirpstack Web UI - register application profile (Collar)
collarProfileId=""

#Obtained from Chirpstack Web UI - register application profile (Gateway)
gatewayProfileId=""

#Obtained from Chirpstack Web UI - register application profile (Gateway)
gatewayId="7812164701badcab"

#Obtained from Chirpstack - used for propper ABP address generation
#in /etc/chirpstack/chirpstack.toml, section [network], net_id
netId="000000"
